#!/bin/bash

inotify_limit=`cat /proc/sys/fs/inotify/max_user_watches`
if [ $inotify_limit -lt 524288 ]; then
  echo "please enter your inotify limit must be increased"
  echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
  sudo sysctl -p
fi


echo "
USER_UID=$(id -u)
USER_GID=$(id -g)
" > .env

docker-compose up

